import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs1: [
    {
      type: 'autogenerated',
      dirName: 'contest',
    },
  ],
  docs2: [
    {
      type: 'autogenerated',
      dirName: 'note',
    },
  ],
  docs3: [
    {
      type: 'autogenerated',
      dirName: 'project',
    },
  ],
};

export default sidebars;
