import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebar1: [
    'contest/index',
    {
      type: 'category',
      label: '个人',
      link: { type: 'generated-index' },
      items: [
        'contest/personal/code-style',
        'contest/personal/code-checker',
        'contest/personal/common-templates',
        'contest/personal/problem-transfer',
      ],
    },
    {
      type: 'category',
      label: '比赛相关',
      link: { type: 'generated-index' },
      items: [
        'contest/contest/noi',
        'contest/contest/problems',
        'contest/contest/tricks',
      ],
    },
  ],
  sidebar2: [
    {
      type: 'autogenerated',
      dirName: 'note',
    },
  ],
  sidebar3: [
    {
      type: 'autogenerated',
      dirName: 'project',
    },
  ],
};

export default sidebars;
