import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs1: [
    {
      type: 'autogenerated',
      dirName: '竞赛',
    },
  ],
  docs2: [
    {
      type: 'autogenerated',
      dirName: '数学',
    },
  ],
  docs3: [
    {
      type: 'autogenerated',
      dirName: '项目',
    },
  ],
  docs4: [
    {
      type: 'autogenerated',
      dirName: '其他',
    },
  ],
};

export default sidebars;
