export interface ProcessedBlogPost {
  title: string;
  date: string;
  permalink: string;
}

interface BlogListItem {
  title?: string;
  date?: string;
  permalink?: string;
  metadata?: {
    title?: string;
    date?: string;
    permalink?: string;
  };
}

interface BlogAuthorSummary {
  key: string;
  name?: string;
  title?: string;
  imageURL?: string;
}

interface BlogTagSummary {
  label?: string;
  permalink?: string;
}

interface BlogPostMetadataSummary {
  permalink: string;
  tags: BlogTagSummary[];
  authors?: BlogAuthorSummary[];
  readingTime?: number;
}

type JsonModule<T> = { default?: T } | T | undefined;

const PINNED_TAG_PATH_SUFFIX = '/blog/tags/pinned';

function resolveJsonModule<T>(mod: JsonModule<T>): T | null {
  if (!mod) {
    return null;
  }
  if (typeof mod === 'object' && 'default' in mod && mod.default) {
    return mod.default as T;
  }
  return mod as T;
}

function normalizePathname(input: string): string {
  if (!input) return '';
  const { pathname } = new URL(input, 'https://example.invalid');
  return pathname.replace(/\/+$/, '');
}

function isPinnedTag(
  tag: { permalink?: string } | string | undefined | null
): boolean {
  if (!tag || typeof tag !== 'object') return false;
  const permalink = tag.permalink;
  if (!permalink) return false;
  const normalized = normalizePathname(permalink);
  return (
    normalized === PINNED_TAG_PATH_SUFFIX ||
    normalized.endsWith(PINNED_TAG_PATH_SUFFIX)
  );
}

/**
 * Collect all blog list items across paginated `blog-post-list-prop-*.json`
 * files generated by the official blog plugin.
 */
export function getAllBlogItems(): BlogListItem[] {
  const ctx = (require as any).context(
    '@generated/docusaurus-plugin-content-blog/default',
    false,
    /blog-post-list-prop-.*\.json$/
  );
  const collected: BlogListItem[] = [];
  ctx.keys().forEach((key: string) => {
    const mod = ctx(key);
    const resolved = resolveJsonModule<{ items?: BlogListItem[] }>(mod);
    collected.push(...(resolved?.items ?? []));
  });
  // Pages overlap, so dedupe by permalink.
  const seen = new Set<string>();
  return collected.filter((it) => {
    const link = it?.permalink ?? it?.metadata?.permalink ?? '';
    if (!link || seen.has(link)) return false;
    seen.add(link);
    return true;
  });
}

/**
 * Read every BlogPostMetadata (including tags) via the `~blog` alias.
 * The official plugin writes these as `createData(hash).json` while building routes.
 */
export function getAllPostMetadata(): BlogPostMetadataSummary[] {
  const list: BlogPostMetadataSummary[] = [];
  const ctx = (require as any).context('~blog/default', false, /\.json$/);
  ctx.keys().forEach((key: string) => {
    const mod = ctx(key);
    const data = resolveJsonModule<BlogPostMetadataSummary>(mod);
    if (data && data.permalink && Array.isArray(data.tags)) {
      list.push(data);
    }
  });
  return list;
}

export function getRecentBlogPosts(maxCount: number = 4): ProcessedBlogPost[] {
  const items = getAllBlogItems();

  const allMetadata = getAllPostMetadata();
  const metadataMap = new Map<string, BlogPostMetadataSummary>();
  allMetadata.forEach((meta) => {
    if (meta.permalink) {
      metadataMap.set(meta.permalink, meta);
    }
  });

  const postsWithMetadata = items
    .map((item) => {
      const permalink = item.permalink ?? item.metadata?.permalink;
      const metadata = permalink ? metadataMap.get(permalink) : undefined;
      const tags = metadata?.tags ?? [];

      return {
        title: item.title ?? item.metadata?.title,
        date: item.date ?? item.metadata?.date,
        permalink,
        isPinned: tags.some(isPinnedTag),
      };
    })
    .filter((post): post is ProcessedBlogPost & { isPinned: boolean } =>
      Boolean(post.permalink && post.title && post.date)
    );

  const sortedPosts = postsWithMetadata.sort((a, b) => {
    if (a.isPinned !== b.isPinned) {
      return a.isPinned ? 1 : -1;
    }
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  return sortedPosts.slice(0, maxCount).map(({ isPinned, ...post }) => post);
}

/**
 * Read the official tag list, preserving Docusaurus' default ordering.
 */
type TagAggregate = {
  label: string;
  permalink: string;
  count: number;
};

const cachedOfficialTags = new Map<string, TagAggregate[]>();

const getLocaleCacheKey = (locale?: string) =>
  locale?.toLowerCase() ?? 'default';

const getLocaleFilePrefix = (locale?: string) =>
  locale ? `${locale.toLowerCase().replace(/_/g, '-')}-` : '';

export function loadOfficialTags(locale?: string): TagAggregate[] {
  const cacheKey = getLocaleCacheKey(locale);
  const cached = cachedOfficialTags.get(cacheKey);
  if (cached) return cached;

  const filePrefix = getLocaleFilePrefix(locale);
  const basePattern = new RegExp(
    `^\\.\/${filePrefix}blog-tags-[a-z0-9]+\\.json$`,
    'i'
  );

  const ctx = (require as any).context(
    '@generated/docusaurus-plugin-content-blog/default/p',
    false,
    /blog-tags-.*\.json$/
  );
  for (const key of ctx.keys()) {
    if (!basePattern.test(key)) continue;
    const mod = ctx(key);
    const data = (mod && (mod.tags ?? mod.default?.tags)) as
      | TagAggregate[]
      | undefined;
    if (Array.isArray(data)) {
      cachedOfficialTags.set(cacheKey, data);
      return data;
    }
  }

  if (locale) {
    const fallback = loadOfficialTags();
    cachedOfficialTags.set(cacheKey, fallback);
    return fallback;
  }

  cachedOfficialTags.set(cacheKey, []);
  return [];
}

export type AuthorAggregate = {
  key: string;
  name?: string;
  page?: { permalink: string };
  count: number;
};

const cachedOfficialAuthors = new Map<string, AuthorAggregate[]>();

export function loadOfficialAuthors(locale?: string): AuthorAggregate[] {
  const cacheKey = getLocaleCacheKey(locale);
  const cached = cachedOfficialAuthors.get(cacheKey);
  if (cached) return cached;

  const filePrefix = getLocaleFilePrefix(locale);
  const basePattern = new RegExp(
    `^\\.\/${filePrefix}blog-authors-[a-z0-9]+\\.json$`,
    'i'
  );

  const ctx = (require as any).context(
    '@generated/docusaurus-plugin-content-blog/default/p',
    false,
    /blog-authors-.*\.json$/
  );
  for (const key of ctx.keys()) {
    if (!basePattern.test(key)) continue;
    const mod = ctx(key);
    const data = (mod && (mod.authors ?? mod.default?.authors)) as
      | AuthorAggregate[]
      | undefined;
    if (Array.isArray(data)) {
      cachedOfficialAuthors.set(cacheKey, data);
      return data;
    }
  }

  if (locale) {
    const fallback = loadOfficialAuthors();
    cachedOfficialAuthors.set(cacheKey, fallback);
    return fallback;
  }

  cachedOfficialAuthors.set(cacheKey, []);
  return [];
}
